import type { Metadata } from "next";
import Navbar from "../components/Navbar/Navbar";
import Toastify from "@/components/Alert/Toastify";
import Footer from "../components/Footer/Footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "DiaryDate | 寫自己・交換日記",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Navbar />
        <main>
          {children}
          <Toastify />
        </main>

        <Footer />
      </body>
    </html>
  );
}
